### ISSUE TITLE
Support disabling / suppressing specific linter warnings

### ISSUE THREAD

**Issue by waldyrious** [JuliaEditorSupport/julia-vscode#194]
I am currently getting several `Use of deprecated parameter syntax` warnings. Using that syntax is deliberate, since I want to keep compatibility with 0.5 without depending on Compat.jl, so I'd like to suppress the warning (for this file/session, at least).

I'm also getting a lot of `Possible use of undeclared variable` in my runtests.jl script, apparently due to the `using` statements not actually importing the corresponding files. Not sure what the best way to handle this is, but if warning suppression were available, it could work for this case as well.

**Comment by adrhill** [comment]
Maybe each warning / linting rule could get a unique code. This approach is taken by [ruff](https://github.com/charliermarsh/ruff) and flake8 in Python.

Copying from the [ruff readme](https://github.com/charliermarsh/ruff#configuration) as an example, this allows for rules to be disabled individually, even on a per-file basis (which would also address #323):
```toml
[tool.ruff]
# Enable Pyflakes and pycodestyle rules.
select = ["E", "F"]

# Never enforce `E501` (line length violations).
ignore = ["E501"]

# Never try to fix `F401` (unused imports).
unfixable = ["F401"]

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"path/to/file.py" = ["E402"]
```

In Python, these are specified in the equivalent of a `Project.toml` (`pyproject.toml`), such that they apply to all contributors of a package.
